import { ExecuteItem, IfElseNodeSchema, IfElseNodeInput, IfElseRule } from "@repo/common/zod";
import { ExecutionContext, ExecutionResult, NodeExecutor } from "../registry/Execution.config.types.js";

export class IfElseNodeExecutor implements NodeExecutor {

    /**
     * Safely traverses an object by dot-separated path (e.g. "user.profile.name")
     */
    private getValueByPath(obj: any, path: string): any {
        if (!obj || typeof obj !== 'object') return undefined;
        const parts = path.split('.');
        let current = obj;
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            if (current === null || current === undefined) return undefined;

            // Support explicit array indices like "[0]" generated by VariablePanel
            const arrayMatch = part!.match(/^\[(\d+)\]$/);
            if (arrayMatch) {
                const index = parseInt(arrayMatch[1]!, 10);
                if (Array.isArray(current)) {
                    current = current[index];
                    continue;
                }
            }

            // ARRAY TRAVERSAL MAGIC: 
            // If we hit an array but there are still parts left (like ".price")
            // Map the remaining path across all array elements!
            if (Array.isArray(current) && isNaN(Number(part))) {
                const remainingPath = parts.slice(i).join('.');
                return current.map(item => this.getValueByPath(item, remainingPath)).filter(v => v !== undefined);
            }

            current = current[part!];
        }
        return current;
    }

    /**
     * Resolves an operand value against the current item.
     * Supports:
     * 1. Variable tags: "{{price}}", "{{status}}", "{{google_sheets.email}}"
     * 2. Plain field keys: "price", "status"
     * 3. Static literals: numbers (200), booleans (true), or raw text ("shipped")
     */
    private resolveOperandValue(operand: any, item: ExecuteItem): any {
        // Guard: check null/undefined explicitly.
        // NOTE: Avoid `if (!operand)` because that would accidentally swallow `0` or `false`!
        if (operand === undefined || operand === null || operand === '') {
            return undefined;
        }

        // Literals like numbers or booleans are returned as-is
        if (typeof operand !== 'string') {
            return operand;
        }

        const trimmed = operand.trim();
        const isWrapped = trimmed.startsWith("{{") && trimmed.endsWith("}}");
        const cleanPath = isWrapped ? trimmed.slice(2, -2).trim() : trimmed;

        const rowData = item.json ?? {};

        // 1. Direct match on rowData (e.g. rowData["price"])
        if (cleanPath in rowData) {
            return rowData[cleanPath];
        }

        // 2. Nested dot lookup (e.g. rowData["customer"]["email"])
        const nestedVal = this.getValueByPath(rowData, cleanPath);
        if (nestedVal !== undefined) {
            return nestedVal;
        }

        // 3. Smart stripping for node-prefixed variables (e.g. {{UUID.[0].json.body.price}})
        // Strips everything up to the first dot, plus any optional array index and 'json' wrappers.
        if (cleanPath.includes('.')) {
            const strippedPath = cleanPath.replace(/^[^.]+\.(?:\[\d+\]\.)?(?:json\.)?/, '');
            const strippedVal = this.getValueByPath(rowData, strippedPath);
            if (strippedVal !== undefined) {
                return strippedVal;
            }

            // Extreme fallback for simple field lookups
            const fieldOnly = cleanPath.split('.').pop()!;
            if (fieldOnly in rowData) {
                return rowData[fieldOnly];
            }
        }

        // 4. If operand was wrapped in {{...}} but not found, it's an unresolved variable
        if (isWrapped) {
            return undefined;
        }

        // 5. Otherwise, treat unadorned string as a literal value (e.g. "shipped", "approved")
        return trimmed;
    }

    /**
     * Evaluates a single comparison rule against an item
     */
    private evaluateRule(rule: IfElseRule, item: ExecuteItem): boolean {
        const val1 = this.resolveOperandValue(rule.operand1, item);
        const val2 = rule.operand2 !== undefined ? this.resolveOperandValue(rule.operand2, item) : undefined;

        const arrayNativeOperators = ['contains', 'not_contains', 'is_empty', 'is_not_empty', 'is_any_of', 'is_not_any_of'];
        if (Array.isArray(val1) && !arrayNativeOperators.includes(rule.operator) && !Array.isArray(val2)) {
            return val1.some(v => {
                // Recursively check each element against the rule
                const subRule = { ...rule, operand1: v };
                return this.evaluateRule(subRule, item); // val1 will now be 'v' because resolveOperandValue handles literal numbers/strings
            });
        }

        switch (rule.operator) {
            // --- Text & General Equality ---
            case 'equals': {
                return this.isSmartEqual(val1, val2)
            }

            case 'not_equals': {
                return !this.isSmartEqual(val1, val2)
            }

            case 'contains': {
                return this.smartContains(val1, val2)
            }

            case 'not_contains': {
                return !this.smartContains(val1, val2)
            }

            case 'starts_with': {
                if (val1 === undefined || val2 === undefined) return false;
                return String(val1).toLowerCase().startsWith(String(val2).toLowerCase());
            }

            case 'ends_with': {
                if (val1 === undefined || val2 === undefined) return false;
                return String(val1).toLowerCase().endsWith(String(val2).toLowerCase());
            }

            case 'regex_match': {
                if (val1 === undefined || val2 === undefined) return false;
                try {
                    const regex = new RegExp(String(val2), "i");
                    return regex.test(String(val1));
                } catch {
                    return false;
                }
            }

            // --- Numeric Comparisons ---
            case 'greater_than': {
                return this.compareOrdered(val1, val2, (a, b) => a > b)
            }

            case 'less_than': {
                return this.compareOrdered(val1, val2, (a, b) => a < b)
            }

            case 'greater_than_or_equal': {
                return this.compareOrdered(val1, val2, (a, b) => a >= b)
            }

            case 'less_than_or_equal': {
                return this.compareOrdered(val1, val2, (a, b) => a <= b)
            }

            // --- List Matching (Comma-separated or Array) ---
            case 'is_any_of': {
                if (val1 === undefined || val2 === undefined) return false;
                const options = Array.isArray(val2)
                    ? val2.map(v => String(v).trim().toLowerCase())
                    : String(val2).split(',').map(s => s.trim().toLowerCase());
                return options.includes(String(val1).trim().toLowerCase());
            }

            case 'is_not_any_of': {
                if (val1 === undefined || val2 === undefined) return true;
                const options = Array.isArray(val2)
                    ? val2.map(v => String(v).trim().toLowerCase())
                    : String(val2).split(',').map(s => s.trim().toLowerCase());
                return !options.includes(String(val1).trim().toLowerCase());
            }

            // --- Unary Checks ---
            case 'is_empty': {
                return this.smartIsEmpty(val1);
            }

            case 'is_not_empty': {
                return !this.smartIsEmpty(val1);
            }

            case 'is_true': {
                const truthyValues = ['1', 'true', 'yes', 'on'];
                return val1 === true || truthyValues.includes(String(val1).trim().toLowerCase());
            }

            case 'is_false': {
                const falsyValues = ['0', 'false', 'no', 'off', ''];
                return val1 === false || val1 === null || val1 === undefined || falsyValues.includes(String(val1).trim().toLowerCase());
            }

            default:
                return false;
        }
    }


    private isSmartEqual(val1: any, val2: any): boolean {
        if (val1 === undefined && val2 === undefined) return true;
        if (val1 === undefined || val2 === undefined) return false;
        if (val1 === null && val2 === null) return true;
        if (val1 === null || val2 === null) return false;

        // 1. Array & Object Deep Comparison
        if (typeof val1 === 'object' && typeof val2 === 'object') {
            try {
                return JSON.stringify(val1) === JSON.stringify(val2);
            } catch {
                return false;
            }
        }

        // 2. Boolean Comparison ("true" === true)
        if (typeof val1 === 'boolean' || typeof val2 === 'boolean') {
            const b1 = typeof val1 === 'boolean' ? val1 : String(val1).trim().toLowerCase() === 'true';
            const b2 = typeof val2 === 'boolean' ? val2 : String(val2).trim().toLowerCase() === 'true';
            return b1 === b2;
        }

        // 3. Numeric Comparison (200 === "200")
        const n1 = Number(val1);
        const n2 = Number(val2);
        if (!isNaN(n1) && !isNaN(n2) && String(val1).trim() !== "" && String(val2).trim() !== "") {
            return n1 === n2;
        }

        // 4. String Normalization
        return String(val1).trim().toLowerCase() === String(val2).trim().toLowerCase();
    }


    private smartContains(val1: any, val2: any): boolean {
        if (val1 === undefined || val2 === undefined || val1 === null || val2 === null) return false;

        // A. Array Member Check
        if (Array.isArray(val1)) {
            return val1.some(item => this.isSmartEqual(item, val2));
        }

        // B. Object Key / Value Check
        if (typeof val1 === 'object') {
            const strVal2 = String(val2).toLowerCase();
            return Object.keys(val1).some(k => k.toLowerCase() === strVal2) ||
                Object.values(val1).some(v => this.isSmartEqual(v, val2));
        }

        // C. String Substring Check
        return String(val1).toLowerCase().includes(String(val2).toLowerCase());
    }

    private compareOrdered(val1: any, val2: any, comparator: (n1: number, n2: number) => boolean): boolean {
        if (val1 === undefined || val2 === undefined || val1 === null || val2 === null) return false;

        // 1. Try Numeric Comparison
        const n1 = Number(val1);
        const n2 = Number(val2);
        if (!isNaN(n1) && !isNaN(n2) && String(val1).trim() !== "" && String(val2).trim() !== "") {
            return comparator(n1, n2);
        }

        // 2. Try Date Comparison
        const d1 = Date.parse(String(val1));
        const d2 = Date.parse(String(val2));
        if (!isNaN(d1) && !isNaN(d2)) {
            return comparator(d1, d2);
        }

        return false;
    }


    private smartIsEmpty(val: any): boolean {
        if (val === undefined || val === null) return true;
        if (typeof val === 'string') return val.trim() === '';
        if (Array.isArray(val)) return val.length === 0;
        if (typeof val === 'object') return Object.keys(val).length === 0;
        return false;
    }


    /**
     * Evaluates a full ExecuteItem against the two-level condition groups
     */
    private evaluateItem(item: ExecuteItem, config: IfElseNodeInput): boolean {
        const groups = config.conditionGroups || [];
        if (groups.length === 0) {
            // Default to false when no rules are configured
            return false;
        }

        const groupResults = groups.map(group => {
            const conditions = group.conditions || [];
            // Guard: empty group should evaluate to false (prevents vacuous truth)
            if (conditions.length === 0) {
                return false;
            }

            if (group.combinator === 'OR') {
                return conditions.some(rule => this.evaluateRule(rule, item));
            } else {
                // Default to 'AND'
                return conditions.every(rule => this.evaluateRule(rule, item));
            }
        });

        if (config.combinator === 'AND') {
            return groupResults.every(Boolean);
        } else {
            // Default to 'OR'
            return groupResults.some(Boolean);
        }
    }

    async execute(context: ExecutionContext): Promise<ExecutionResult> {
        try {
            const inputConfig = Array.isArray(context.config) ? context.config[0] || {} : context.config || {};
            const parsed = IfElseNodeSchema.safeParse(inputConfig);

            if (!parsed.success) {
                return {
                    success: false,
                    error: "Invalid If/Else configuration: " + parsed.error.issues.map(e => e.message).join(", ")
                };
            }

            const config = parsed.data;
            const items = (context.items && context.items.length > 0)
                ? context.items
                : [{ json: {} }];

            const trueItems: ExecuteItem[] = [];
            const falseItems: ExecuteItem[] = [];
            const evaluationErrors: Array<{ rowIndex: number, error: string }> = [];
            for (let i = 0; i < items.length; i++) {
                const item = items[i]!;
                let passed = false;
                try {
                    passed = this.evaluateItem(item, config);
                } catch (err: any) {
                    passed = false; // Force it to the False branch
                    evaluationErrors.push({ rowIndex: i, error: err.message || String(err) });
                }

                if (passed) {
                    trueItems.push({
                        json: item.json,
                        sourceRefs: {
                            ...(item.sourceRefs || {}),
                            [context.nodeId]: { wireIndex: 0, rowIndex: trueItems.length }
                        }
                    });
                } else {
                    falseItems.push({
                        json: item.json,
                        sourceRefs: {
                            ...(item.sourceRefs || {}),
                            [context.nodeId]: { wireIndex: 1, rowIndex: falseItems.length }
                        }
                    });
                }
            }

            return {
                success: true,
                output: [trueItems, falseItems],
                metadata: {
                    total_processed: items.length,
                    true_count: trueItems.length,
                    false_count: falseItems.length,
                    errors: evaluationErrors.length > 0 ? evaluationErrors : undefined,
                    // Schema fallback for empty branches so downstream VariablePanel works
                    schema: items[0]?.json ? Object.keys(items[0].json) : []
                }
            };
        } catch (error: any) {
            return {
                success: false,
                error: error instanceof Error ? error.message : String(error)
            };
        }
    }
}